# Generated by Django 4.2.1 on 2023-05-20 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0005_alter_fotografia_data_fotografia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotografia",
            name="data_fotografia",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 20, 11, 5, 20, 986402)
            ),
        ),
    ]
